<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="11.11.*" />
    <PackageReference Include="MediatR" Version="12.4.*" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.*" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\NT.QAMS.Domain\NT.QAMS.Domain.csproj" />
    <ProjectReference Include="..\NT.QAMS.Contracts\NT.QAMS.Contracts.csproj" />
  </ItemGroup>

</Project>
