<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.105.0" />
    <PackageReference Include="EFCore.NamingConventions" Version="9.0.*" />
    <PackageReference Include="Microsoft.Extensions.Identity.Core" Version="9.0.*" />
    <PackageReference Include="QuestPDF" Version="2026.7.1" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.2.*" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.*" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="9.0.*" />
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.Abstractions" Version="9.0.*" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="9.0.*" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\NT.QAMS.Application\NT.QAMS.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="NT.QAMS.Application.UnitTests" />
    <InternalsVisibleTo Include="NT.QAMS.IntegrationTests" />
  </ItemGroup>

</Project>
