// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NT.QAMS.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NT.QAMS.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260721223052_GovernanceAndSuppliers")]
    partial class GovernanceAndSuppliers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NT.QAMS.Domain.AuditManagement.Audit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AuditRef")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("audit_ref");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<Guid>("LeadAuditorId")
                        .HasColumnType("uuid")
                        .HasColumnName("lead_auditor_id");

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at_utc");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modified_by");

                    b.Property<DateOnly>("PlannedDate")
                        .HasColumnType("date")
                        .HasColumnName("planned_date");

                    b.Property<DateTimeOffset?>("SignedOffAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("signed_off_at_utc");

                    b.Property<Guid?>("SignedOffBy")
                        .HasColumnType("uuid")
                        .HasColumnName("signed_off_by");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_audit");

                    b.HasIndex("TenantId", "AuditRef")
                        .IsUnique()
                        .HasDatabaseName("ix_audit_tenant_id_audit_ref");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("ix_audit_tenant_id_status");

                    b.ToTable("audit", "qams");
                });

            modelBuilder.Entity("NT.QAMS.Domain.Competency.CompetencyRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AuthorizedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("authorized_by");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<Guid?>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<DateOnly?>("ExpiresAt")
                        .HasColumnType("date")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at_utc");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modified_by");

                    b.Property<string>("RevocationReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("revocation_reason");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("subject");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("TraineeId")
                        .HasColumnType("uuid")
                        .HasColumnName("trainee_id");

                    b.Property<int>("ValidityMonths")
                        .HasColumnType("integer")
                        .HasColumnName("validity_months");

                    b.HasKey("Id")
                        .HasName("pk_competency_record");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("ix_competency_record_tenant_id_status");

                    b.HasIndex("TenantId", "TraineeId")
                        .HasDatabaseName("ix_competency_record_tenant_id_trainee_id");

                    b.ToTable("competency_record", "qams");
                });

            modelBuilder.Entity("NT.QAMS.Domain.Competency.TrainingAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Completed")
                        .HasColumnType("boolean")
                        .HasColumnName("completed");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<Guid?>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("due_date");

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at_utc");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modified_by");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("subject");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("TraineeId")
                        .HasColumnType("uuid")
                        .HasColumnName("trainee_id");

                    b.HasKey("Id")
                        .HasName("pk_training_assignment");

                    b.HasIndex("TenantId", "TraineeId", "Completed")
                        .HasDatabaseName("ix_training_assignment_tenant_id_trainee_id_completed");

                    b.ToTable("training_assignment", "qams");
                });

            modelBuilder.Entity("NT.QAMS.Domain.DocumentControl.ControlledDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("category");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at_utc");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modified_by");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_controlled_document");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_controlled_document_tenant_id_code");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("ix_controlled_document_tenant_id_status");

                    b.ToTable("controlled_document", "qams");
                });

            modelBuilder.Entity("NT.QAMS.Domain.Equipment.EquipmentItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("CalibrationIntervalDays")
                        .HasColumnType("integer")
                        .HasColumnName("calibration_interval_days");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<int>("GracePeriodDays")
                        .HasColumnType("integer")
                        .HasColumnName("grace_period_days");

                    b.Property<DateOnly?>("LastCalibrationAt")
                        .HasColumnType("date")
                        .HasColumnName("last_calibration_at");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("location");

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at_utc");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modified_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateOnly?>("NextCalibrationDue")
                        .HasColumnType("date")
                        .HasColumnName("next_calibration_due");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("serial_number");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_equipment_item");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_equipment_item_tenant_id_code");

                    b.HasIndex("TenantId", "SerialNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_equipment_item_tenant_id_serial_number");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("ix_equipment_item_tenant_id_status");

                    b.ToTable("equipment_item", "qams");
                });

            modelBuilder.Entity("NT.QAMS.Domain.Files.FileReference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)")
                        .HasColumnName("file_name");

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at_utc");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modified_by");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("sha256");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("storage_key");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_file_reference");

                    b.HasIndex("TenantId", "Sha256")
                        .HasDatabaseName("ix_file_reference_tenant_id_sha256");

                    b.ToTable("file_reference", "qams");
                });

            modelBuilder.Entity("NT.QAMS.Domain.IdentityAccess.UserAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at_utc");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modified_by");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("role");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_user_account");

                    b.HasIndex("TenantId", "Email")
                        .IsUnique()
                        .HasDatabaseName("ix_user_account_tenant_id_email");

                    b.ToTable("user_account", "qams");
                });

            modelBuilder.Entity("NT.QAMS.Domain.Improvement.Nonconformance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AssignedTo")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_to");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("description");

                    b.Property<int>("Likelihood")
                        .HasColumnType("integer")
                        .HasColumnName("likelihood");

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at_utc");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modified_by");

                    b.Property<string>("NcRef")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("nc_ref");

                    b.Property<Guid>("RaisedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("raised_by");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("rejection_reason");

                    b.Property<int>("Rpn")
                        .HasColumnType("integer")
                        .HasColumnName("rpn");

                    b.Property<int>("Severity")
                        .HasColumnType("integer")
                        .HasColumnName("severity");

                    b.Property<string>("SourceRef")
                        .HasColumnType("text")
                        .HasColumnName("source_ref");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("source_type");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_nonconformance");

                    b.HasIndex("TenantId", "NcRef")
                        .IsUnique()
                        .HasDatabaseName("ix_nonconformance_tenant_id_nc_ref");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("ix_nonconformance_tenant_id_status");

                    b.ToTable("nonconformance", "qams");
                });

            modelBuilder.Entity("NT.QAMS.Domain.RiskGovernance.ChangeRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ApprovedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at_utc");

                    b.Property<Guid?>("ApprovedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("approved_by");

                    b.Property<string>("ChangeRef")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("change_ref");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("ImpactAnalysis")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("impact_analysis");

                    b.Property<string>("ImplementationNotes")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("implementation_notes");

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at_utc");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modified_by");

                    b.Property<Guid>("ProposedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("proposed_by");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("rejection_reason");

                    b.Property<Guid?>("RiskItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("risk_item_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_change_request");

                    b.HasIndex("TenantId", "ChangeRef")
                        .IsUnique()
                        .HasDatabaseName("ix_change_request_tenant_id_change_ref");

                    b.ToTable("change_request", "qams");
                });

            modelBuilder.Entity("NT.QAMS.Domain.RiskGovernance.ManagementReview", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ClosedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("closed_by");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Minutes")
                        .HasMaxLength(20000)
                        .HasColumnType("character varying(20000)")
                        .HasColumnName("minutes");

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at_utc");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modified_by");

                    b.Property<string>("Participants")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("participants");

                    b.Property<DateOnly>("ReviewDate")
                        .HasColumnType("date")
                        .HasColumnName("review_date");

                    b.Property<string>("ReviewRef")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("review_ref");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_management_review");

                    b.HasIndex("TenantId", "ReviewRef")
                        .IsUnique()
                        .HasDatabaseName("ix_management_review_tenant_id_review_ref");

                    b.ToTable("management_review", "qams");
                });

            modelBuilder.Entity("NT.QAMS.Domain.RiskGovernance.RiskItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<int>("Impact")
                        .HasColumnType("integer")
                        .HasColumnName("impact");

                    b.Property<int>("Likelihood")
                        .HasColumnType("integer")
                        .HasColumnName("likelihood");

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at_utc");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modified_by");

                    b.Property<int?>("ResidualImpact")
                        .HasColumnType("integer")
                        .HasColumnName("residual_impact");

                    b.Property<int?>("ResidualLikelihood")
                        .HasColumnType("integer")
                        .HasColumnName("residual_likelihood");

                    b.Property<int?>("ResidualRpn")
                        .HasColumnType("integer")
                        .HasColumnName("residual_rpn");

                    b.Property<string>("RiskRef")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("risk_ref");

                    b.Property<int>("Rpn")
                        .HasColumnType("integer")
                        .HasColumnName("rpn");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_risk_item");

                    b.HasIndex("TenantId", "RiskRef")
                        .IsUnique()
                        .HasDatabaseName("ix_risk_item_tenant_id_risk_ref");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("ix_risk_item_tenant_id_status");

                    b.ToTable("risk_item", "qams");
                });

            modelBuilder.Entity("NT.QAMS.Domain.SupplierQuality.Supplier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ApprovedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("approved_by");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at_utc");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modified_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("RegisteredBy")
                        .HasColumnType("uuid")
                        .HasColumnName("registered_by");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("status");

                    b.Property<string>("SupplierRef")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("supplier_ref");

                    b.Property<string>("SupplierType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("supplier_type");

                    b.Property<string>("SuspensionReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("suspension_reason");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_supplier");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("ix_supplier_tenant_id_status");

                    b.HasIndex("TenantId", "SupplierRef")
                        .IsUnique()
                        .HasDatabaseName("ix_supplier_tenant_id_supplier_ref");

                    b.ToTable("supplier", "qams");
                });

            modelBuilder.Entity("NT.QAMS.Domain.SupplierQuality.SupplierEvaluation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("CriteriaJson")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)")
                        .HasColumnName("criteria_json");

                    b.Property<Guid>("EvaluatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("evaluated_by");

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at_utc");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modified_by");

                    b.Property<DateOnly>("PeriodEnd")
                        .HasColumnType("date")
                        .HasColumnName("period_end");

                    b.Property<DateOnly>("PeriodStart")
                        .HasColumnType("date")
                        .HasColumnName("period_start");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uuid")
                        .HasColumnName("supplier_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<decimal>("WeightedTotal")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("weighted_total");

                    b.HasKey("Id")
                        .HasName("pk_supplier_evaluation");

                    b.HasIndex("TenantId", "SupplierId")
                        .HasDatabaseName("ix_supplier_evaluation_tenant_id_supplier_id");

                    b.ToTable("supplier_evaluation", "qams");
                });

            modelBuilder.Entity("NT.QAMS.Domain.Tenancy.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("ModifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at_utc");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modified_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("identifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("SuspensionReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("suspension_reason");

                    b.HasKey("Id")
                        .HasName("pk_tenant");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_tenant_identifier");

                    b.ToTable("tenant", "saas");
                });

            modelBuilder.Entity("NT.QAMS.Infrastructure.Persistence.Outbox.OutboxEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("event_type");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at_utc");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_outbox_event");

                    b.HasIndex("OccurredAtUtc")
                        .HasDatabaseName("ix_outbox_event_pending")
                        .HasFilter("processed_at_utc IS NULL");

                    b.ToTable("outbox_event", "qams");
                });

            modelBuilder.Entity("NT.QAMS.Infrastructure.Persistence.RefCounter", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("RefType")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("ref_type");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.Property<long>("LastValue")
                        .HasColumnType("bigint")
                        .HasColumnName("last_value");

                    b.HasKey("TenantId", "RefType", "Year")
                        .HasName("pk_ref_counter");

                    b.ToTable("ref_counter", "qams");
                });

            modelBuilder.Entity("NT.QAMS.Domain.AuditManagement.Audit", b =>
                {
                    b.OwnsMany("NT.QAMS.Domain.AuditManagement.AuditChecklistItem", "Checklist", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Evidence")
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("evidence");

                            b1.Property<string>("IsoClause")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)")
                                .HasColumnName("iso_clause");

                            b1.Property<string>("Question")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("question");

                            b1.Property<string>("Verdict")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("verdict");

                            b1.Property<Guid>("audit_id")
                                .HasColumnType("uuid")
                                .HasColumnName("audit_id");

                            b1.HasKey("Id")
                                .HasName("pk_audit_checklist_item");

                            b1.HasIndex("audit_id")
                                .HasDatabaseName("ix_audit_checklist_item_audit_id");

                            b1.ToTable("audit_checklist_item", "qams");

                            b1.WithOwner()
                                .HasForeignKey("audit_id")
                                .HasConstraintName("fk_audit_checklist_item_audit_audit_id");
                        });

                    b.OwnsMany("NT.QAMS.Domain.AuditManagement.AuditFinding", "Findings", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasMaxLength(4000)
                                .HasColumnType("character varying(4000)")
                                .HasColumnName("description");

                            b1.Property<string>("Grade")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("grade");

                            b1.Property<Guid?>("NcId")
                                .HasColumnType("uuid")
                                .HasColumnName("nc_id");

                            b1.Property<Guid>("audit_id")
                                .HasColumnType("uuid")
                                .HasColumnName("audit_id");

                            b1.HasKey("Id")
                                .HasName("pk_audit_finding");

                            b1.HasIndex("audit_id")
                                .HasDatabaseName("ix_audit_finding_audit_id");

                            b1.ToTable("audit_finding", "qams");

                            b1.WithOwner()
                                .HasForeignKey("audit_id")
                                .HasConstraintName("fk_audit_finding_audit_audit_id");
                        });

                    b.Navigation("Checklist");

                    b.Navigation("Findings");
                });

            modelBuilder.Entity("NT.QAMS.Domain.Competency.CompetencyRecord", b =>
                {
                    b.OwnsMany("NT.QAMS.Domain.Competency.AssessmentResult", "Assessments", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTimeOffset>("AssessedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("assessed_at_utc");

                            b1.Property<Guid>("AssessorId")
                                .HasColumnType("uuid")
                                .HasColumnName("assessor_id");

                            b1.Property<int>("Score")
                                .HasColumnType("integer")
                                .HasColumnName("score");

                            b1.Property<Guid>("competency_id")
                                .HasColumnType("uuid")
                                .HasColumnName("competency_id");

                            b1.HasKey("Id")
                                .HasName("pk_assessment_result");

                            b1.HasIndex("competency_id")
                                .HasDatabaseName("ix_assessment_result_competency_id");

                            b1.ToTable("assessment_result", "qams");

                            b1.WithOwner()
                                .HasForeignKey("competency_id")
                                .HasConstraintName("fk_assessment_result_competency_record_competency_id");
                        });

                    b.Navigation("Assessments");
                });

            modelBuilder.Entity("NT.QAMS.Domain.DocumentControl.ControlledDocument", b =>
                {
                    b.OwnsMany("NT.QAMS.Domain.DocumentControl.DocumentVersion", "Versions", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTimeOffset?>("ApprovedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("approved_at_utc");

                            b1.Property<Guid?>("ApprovedBy")
                                .HasColumnType("uuid")
                                .HasColumnName("approved_by");

                            b1.Property<Guid>("AuthorId")
                                .HasColumnType("uuid")
                                .HasColumnName("author_id");

                            b1.Property<string>("ChangeSummary")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("change_summary");

                            b1.Property<Guid>("FileId")
                                .HasColumnType("uuid")
                                .HasColumnName("file_id");

                            b1.Property<int>("Major")
                                .HasColumnType("integer")
                                .HasColumnName("major");

                            b1.Property<int>("Minor")
                                .HasColumnType("integer")
                                .HasColumnName("minor");

                            b1.Property<DateTimeOffset?>("RecommendedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("recommended_at_utc");

                            b1.Property<Guid?>("RecommendedBy")
                                .HasColumnType("uuid")
                                .HasColumnName("recommended_by");

                            b1.Property<string>("RejectionReason")
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("rejection_reason");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("state");

                            b1.Property<Guid>("document_id")
                                .HasColumnType("uuid")
                                .HasColumnName("document_id");

                            b1.HasKey("Id")
                                .HasName("pk_document_version");

                            b1.HasIndex("document_id")
                                .HasDatabaseName("ix_document_version_document_id");

                            b1.ToTable("document_version", "qams");

                            b1.WithOwner()
                                .HasForeignKey("document_id")
                                .HasConstraintName("fk_document_version_controlled_document_document_id");
                        });

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("NT.QAMS.Domain.Equipment.EquipmentItem", b =>
                {
                    b.OwnsMany("NT.QAMS.Domain.Equipment.CalibrationRecord", "Calibrations", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<Guid?>("CertificateFileId")
                                .HasColumnType("uuid")
                                .HasColumnName("certificate_file_id");

                            b1.Property<DateOnly>("PerformedAt")
                                .HasColumnType("date")
                                .HasColumnName("performed_at");

                            b1.Property<string>("Provider")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("provider");

                            b1.Property<string>("Result")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("result");

                            b1.Property<Guid>("equipment_id")
                                .HasColumnType("uuid")
                                .HasColumnName("equipment_id");

                            b1.HasKey("Id")
                                .HasName("pk_calibration_record");

                            b1.HasIndex("equipment_id")
                                .HasDatabaseName("ix_calibration_record_equipment_id");

                            b1.ToTable("calibration_record", "qams");

                            b1.WithOwner()
                                .HasForeignKey("equipment_id")
                                .HasConstraintName("fk_calibration_record_equipment_item_equipment_id");
                        });

                    b.OwnsMany("NT.QAMS.Domain.Equipment.MaintenanceRecord", "Maintenance", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateOnly>("PerformedAt")
                                .HasColumnType("date")
                                .HasColumnName("performed_at");

                            b1.Property<string>("WorkDescription")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("work_description");

                            b1.Property<Guid>("equipment_id")
                                .HasColumnType("uuid")
                                .HasColumnName("equipment_id");

                            b1.HasKey("Id")
                                .HasName("pk_maintenance_record");

                            b1.HasIndex("equipment_id")
                                .HasDatabaseName("ix_maintenance_record_equipment_id");

                            b1.ToTable("maintenance_record", "qams");

                            b1.WithOwner()
                                .HasForeignKey("equipment_id")
                                .HasConstraintName("fk_maintenance_record_equipment_item_equipment_id");
                        });

                    b.Navigation("Calibrations");

                    b.Navigation("Maintenance");
                });

            modelBuilder.Entity("NT.QAMS.Domain.Improvement.Nonconformance", b =>
                {
                    b.OwnsMany("NT.QAMS.Domain.Improvement.CapaAction", "CapaActions", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTimeOffset?>("CompletedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("completed_at_utc");

                            b1.Property<string>("Details")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("details");

                            b1.Property<DateOnly>("DueDate")
                                .HasColumnType("date")
                                .HasColumnName("due_date");

                            b1.Property<Guid>("OwnerId")
                                .HasColumnType("uuid")
                                .HasColumnName("owner_id");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("status");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("type");

                            b1.Property<Guid>("nc_id")
                                .HasColumnType("uuid")
                                .HasColumnName("nc_id");

                            b1.HasKey("Id")
                                .HasName("pk_capa_action");

                            b1.HasIndex("nc_id")
                                .HasDatabaseName("ix_capa_action_nc_id");

                            b1.ToTable("capa_action", "qams");

                            b1.WithOwner()
                                .HasForeignKey("nc_id")
                                .HasConstraintName("fk_capa_action_nonconformance_nc_id");
                        });

                    b.OwnsMany("NT.QAMS.Domain.Improvement.RcaRecord", "RcaRecords", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Analysis")
                                .IsRequired()
                                .HasMaxLength(8000)
                                .HasColumnType("character varying(8000)")
                                .HasColumnName("analysis");

                            b1.Property<Guid>("InvestigatorId")
                                .HasColumnType("uuid")
                                .HasColumnName("investigator_id");

                            b1.Property<string>("Method")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("method");

                            b1.Property<Guid>("nc_id")
                                .HasColumnType("uuid")
                                .HasColumnName("nc_id");

                            b1.HasKey("Id")
                                .HasName("pk_rca_record");

                            b1.HasIndex("nc_id")
                                .HasDatabaseName("ix_rca_record_nc_id");

                            b1.ToTable("rca_record", "qams");

                            b1.WithOwner()
                                .HasForeignKey("nc_id")
                                .HasConstraintName("fk_rca_record_nonconformance_nc_id");
                        });

                    b.Navigation("CapaActions");

                    b.Navigation("RcaRecords");
                });

            modelBuilder.Entity("NT.QAMS.Domain.RiskGovernance.ManagementReview", b =>
                {
                    b.OwnsMany("NT.QAMS.Domain.RiskGovernance.ReviewDecision", "Decisions", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("description");

                            b1.Property<DateOnly>("DueDate")
                                .HasColumnType("date")
                                .HasColumnName("due_date");

                            b1.Property<Guid>("OwnerId")
                                .HasColumnType("uuid")
                                .HasColumnName("owner_id");

                            b1.Property<Guid>("review_id")
                                .HasColumnType("uuid")
                                .HasColumnName("review_id");

                            b1.HasKey("Id")
                                .HasName("pk_review_decision");

                            b1.HasIndex("review_id")
                                .HasDatabaseName("ix_review_decision_review_id");

                            b1.ToTable("review_decision", "qams");

                            b1.WithOwner()
                                .HasForeignKey("review_id")
                                .HasConstraintName("fk_review_decision_management_review_review_id");
                        });

                    b.Navigation("Decisions");
                });

            modelBuilder.Entity("NT.QAMS.Domain.RiskGovernance.RiskItem", b =>
                {
                    b.OwnsMany("NT.QAMS.Domain.RiskGovernance.MitigationAction", "Actions", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<bool>("Completed")
                                .HasColumnType("boolean")
                                .HasColumnName("completed");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("description");

                            b1.Property<DateOnly>("DueDate")
                                .HasColumnType("date")
                                .HasColumnName("due_date");

                            b1.Property<Guid>("OwnerId")
                                .HasColumnType("uuid")
                                .HasColumnName("owner_id");

                            b1.Property<Guid>("risk_id")
                                .HasColumnType("uuid")
                                .HasColumnName("risk_id");

                            b1.HasKey("Id")
                                .HasName("pk_mitigation_action");

                            b1.HasIndex("risk_id")
                                .HasDatabaseName("ix_mitigation_action_risk_id");

                            b1.ToTable("mitigation_action", "qams");

                            b1.WithOwner()
                                .HasForeignKey("risk_id")
                                .HasConstraintName("fk_mitigation_action_risk_item_risk_id");
                        });

                    b.Navigation("Actions");
                });

            modelBuilder.Entity("NT.QAMS.Domain.SupplierQuality.Supplier", b =>
                {
                    b.OwnsMany("NT.QAMS.Domain.SupplierQuality.CertificateRecord", "Certificates", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("CertificateType")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("certificate_type");

                            b1.Property<DateOnly>("ExpiresAt")
                                .HasColumnType("date")
                                .HasColumnName("expires_at");

                            b1.Property<Guid?>("FileId")
                                .HasColumnType("uuid")
                                .HasColumnName("file_id");

                            b1.Property<Guid>("supplier_id")
                                .HasColumnType("uuid")
                                .HasColumnName("supplier_id");

                            b1.HasKey("Id")
                                .HasName("pk_supplier_certificate");

                            b1.HasIndex("supplier_id")
                                .HasDatabaseName("ix_supplier_certificate_supplier_id");

                            b1.ToTable("supplier_certificate", "qams");

                            b1.WithOwner()
                                .HasForeignKey("supplier_id")
                                .HasConstraintName("fk_supplier_certificate_supplier_supplier_id");
                        });

                    b.Navigation("Certificates");
                });

            modelBuilder.Entity("NT.QAMS.Domain.Tenancy.Tenant", b =>
                {
                    b.OwnsOne("NT.QAMS.Domain.Tenancy.TenantSettings", "Settings", b1 =>
                        {
                            b1.Property<Guid>("TenantId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<int>("CalibrationReminderDays")
                                .HasColumnType("integer")
                                .HasColumnName("calibration_reminder_days");

                            b1.Property<string>("DefaultLanguage")
                                .IsRequired()
                                .HasMaxLength(5)
                                .HasColumnType("character varying(5)")
                                .HasColumnName("default_language");

                            b1.Property<int>("PasswordExpiryDays")
                                .HasColumnType("integer")
                                .HasColumnName("password_expiry_days");

                            b1.Property<int>("SopExpiryReminderMonths")
                                .HasColumnType("integer")
                                .HasColumnName("sop_expiry_reminder_months");

                            b1.Property<string>("TimeZone")
                                .IsRequired()
                                .HasMaxLength(60)
                                .HasColumnType("character varying(60)")
                                .HasColumnName("time_zone");

                            b1.HasKey("TenantId");

                            b1.ToTable("tenant", "saas");

                            b1.WithOwner()
                                .HasForeignKey("TenantId")
                                .HasConstraintName("fk_tenant_tenant_id");
                        });

                    b.Navigation("Settings")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
