using ClosedXML.Excel;
using NT.QAMS.Application.Abstractions;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace NT.QAMS.Infrastructure.Exports;

/// <summary>
/// Part 11 §11.10(b) export rendering: real XLSX via ClosedXML (one worksheet
/// per table, provenance header, frozen header row) and paginated PDF via
/// QuestPDF (Community license) with the provenance stamp in every page
/// footer. Deliberately no HTML-as-xls tricks — these are inspection copies.
/// </summary>
public sealed class ExportService : IExportService
{
    static ExportService()
    {
        QuestPDF.Settings.License = LicenseType.Community;
    }

    public byte[] ToXlsx(ExportPack pack)
    {
        using var workbook = new XLWorkbook();
        var index = 1;
        foreach (var table in pack.Tables)
        {
            var sheet = workbook.Worksheets.Add(SheetName(table.Title, index++));

            sheet.Cell(1, 1).Value = pack.Title;
            sheet.Cell(1, 1).Style.Font.SetBold().Font.SetFontSize(14);
            sheet.Cell(2, 1).Value =
                $"Tenant: {pack.TenantName} · Generated by {pack.GeneratedBy} at {pack.GeneratedAtUtc:u} · {table.Title}";
            sheet.Cell(2, 1).Style.Font.SetItalic().Font.SetFontColor(XLColor.DimGray);

            const int headerRow = 4;
            for (var c = 0; c < table.Columns.Count; c++)
            {
                var cell = sheet.Cell(headerRow, c + 1);
                cell.Value = table.Columns[c];
                cell.Style.Font.SetBold();
                cell.Style.Fill.SetBackgroundColor(XLColor.FromHtml("#3B4658"));
                cell.Style.Font.SetFontColor(XLColor.White);
            }

            for (var r = 0; r < table.Rows.Count; r++)
            {
                for (var c = 0; c < table.Rows[r].Count; c++)
                {
                    sheet.Cell(headerRow + 1 + r, c + 1).Value = table.Rows[r][c];
                }
            }

            sheet.SheetView.FreezeRows(headerRow);
            sheet.Columns().AdjustToContents(1, Math.Min(headerRow + 50, headerRow + table.Rows.Count + 1));
        }

        using var stream = new MemoryStream();
        workbook.SaveAs(stream);
        return stream.ToArray();
    }

    public byte[] ToPdf(ExportPack pack)
    {
        return Document.Create(document => document.Page(page =>
        {
            page.Size(PageSizes.A4.Landscape());
            page.Margin(28);
            page.DefaultTextStyle(t => t.FontSize(9));

            page.Header().Column(header =>
            {
                header.Item().Text(pack.Title).Bold().FontSize(16).FontColor("#1E3A5F");
                header.Item().PaddingBottom(6).Text($"Tenant: {pack.TenantName}")
                    .FontSize(9).FontColor("#666666");
            });

            page.Content().Column(content =>
            {
                foreach (var table in pack.Tables)
                {
                    content.Item().PaddingTop(10).Text(table.Title).Bold().FontSize(11).FontColor("#3B4658");
                    content.Item().PaddingTop(4).Table(t =>
                    {
                        t.ColumnsDefinition(cols =>
                        {
                            foreach (var _ in table.Columns)
                            {
                                cols.RelativeColumn();
                            }
                        });

                        t.Header(h =>
                        {
                            foreach (var column in table.Columns)
                            {
                                h.Cell().Background("#3B4658").Padding(4)
                                    .Text(column).Bold().FontColor("#FFFFFF").FontSize(8.5f);
                            }
                        });

                        var zebra = false;
                        foreach (var row in table.Rows)
                        {
                            var background = zebra ? "#F7F7F7" : "#FFFFFF";
                            zebra = !zebra;
                            foreach (var value in row)
                            {
                                t.Cell().Background(background).BorderBottom(0.5f).BorderColor("#C1C1C6")
                                    .Padding(4).Text(value).FontSize(8.5f);
                            }
                        }
                    });
                }
            });

            page.Footer().Row(footer =>
            {
                footer.RelativeItem().Text(
                        $"Accurate and complete copy · generated by {pack.GeneratedBy} at {pack.GeneratedAtUtc:u}")
                    .FontSize(7.5f).FontColor("#797979");
                footer.RelativeItem().AlignRight().Text(t =>
                {
                    t.DefaultTextStyle(s => s.FontSize(7.5f).FontColor("#797979"));
                    t.Span("Page ");
                    t.CurrentPageNumber();
                    t.Span(" of ");
                    t.TotalPages();
                });
            });
        })).GeneratePdf();
    }

    /// <summary>Worksheet names cap at 31 chars and must be unique per workbook.</summary>
    private static string SheetName(string title, int index)
    {
        var cleaned = new string(title.Where(ch => ch is not ('\\' or '/' or '*' or '[' or ']' or ':' or '?')).ToArray());
        var trimmed = cleaned.Length > 27 ? cleaned[..27] : cleaned;
        return $"{index:00} {trimmed}".Trim();
    }
}
