using NT.QAMS.Application.Abstractions;
using NT.QAMS.Contracts.Common;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace NT.QAMS.Infrastructure.Exports;

/// <summary>
/// The professional User Manual renderer. Kept in its own partial. Produces a
/// cover with a topics-per-section overview chart, a linked table of contents,
/// and one card per topic mirroring the in-app help — a plain-language summary, a
/// numbered progress bar over the workflow steps, the steps with their detail, and
/// the "how to use" checklist — in the shared brand palette, with the provenance
/// stamp on every page. The content is the SPA's help catalogue, localized by the
/// caller; this only lays it out.
/// </summary>
public sealed partial class ExportService
{
    public byte[] ToManualPdf(ManualExportPack pack)
    {
        var totalTopics = pack.Groups.Sum(g => g.Topics.Count);
        var maxTopics = pack.Groups.Count == 0 ? 1 : Math.Max(1, pack.Groups.Max(g => g.Topics.Count));

        return Document.Create(document => document.Page(page =>
        {
            page.Size(PageSizes.A4);
            page.Margin(34);
            page.DefaultTextStyle(t => t.FontSize(10).FontColor(Slate));

            page.Content().Column(root =>
            {
                // ── Cover ──────────────────────────────────────────────────────
                root.Item().PaddingTop(40).BorderBottom(3).BorderColor(Blue).PaddingBottom(10).Column(cover =>
                {
                    cover.Item().Text("User Manual").Bold().FontSize(30).FontColor(Navy);
                    cover.Item().PaddingTop(2).Text("NT.QAMS — Laboratory Quality & Compliance Platform")
                        .FontSize(12).FontColor(Teal).Bold();
                });
                root.Item().PaddingTop(14).Row(meta =>
                {
                    meta.RelativeItem().Column(c =>
                    {
                        c.Item().Text(pack.TenantName).FontSize(11).Bold();
                        c.Item().Text($"Language: {pack.Language.ToUpperInvariant()}").FontSize(9).FontColor("#666666");
                    });
                    meta.ConstantItem(220).AlignRight().Column(c =>
                    {
                        c.Item().AlignRight().Text($"{pack.GeneratedAtUtc:yyyy-MM-dd HH:mm} UTC").FontSize(9).FontColor("#666666");
                        c.Item().AlignRight().Text($"Generated by {pack.GeneratedBy}").FontSize(9).FontColor("#666666");
                    });
                });

                root.Item().PaddingTop(18).Row(stats =>
                {
                    OverviewTile(stats.RelativeItem(), totalTopics.ToString(), "Topics documented");
                    OverviewTile(stats.RelativeItem(), pack.Groups.Count.ToString(), "Sections");
                });

                root.Item().PaddingTop(16).Text("Coverage by section").Bold().FontSize(11).FontColor(Navy);
                root.Item().PaddingTop(6).Column(chart =>
                {
                    foreach (var g in pack.Groups)
                    {
                        var pct = (int)Math.Round(100.0 * g.Topics.Count / maxTopics, MidpointRounding.AwayFromZero);
                        chart.Item().PaddingBottom(3).Row(row =>
                        {
                            row.ConstantItem(150).Text(g.Title).FontSize(8.5f);
                            row.RelativeItem().AlignMiddle().Height(11).Row(bar =>
                            {
                                if (pct > 0) { bar.RelativeItem(pct).Background(InkFor("blue")); }
                                if (pct < 100) { bar.RelativeItem(100 - pct).Background(GreyBg); }
                            });
                            row.ConstantItem(30).AlignRight().Text(g.Topics.Count.ToString()).FontSize(8.5f).Bold();
                        });
                    }
                });

                root.Item().PageBreak();

                // ── Table of contents ──────────────────────────────────────────
                root.Item().Text("Contents").Bold().FontSize(16).FontColor(Navy);
                root.Item().PaddingTop(6).Column(toc =>
                {
                    for (var gi = 0; gi < pack.Groups.Count; gi++)
                    {
                        var g = pack.Groups[gi];
                        toc.Item().PaddingTop(gi == 0 ? 0 : 8).Text($"{gi + 1}. {g.Title}")
                            .Bold().FontSize(10.5f).FontColor(Slate);
                        for (var ti = 0; ti < g.Topics.Count; ti++)
                        {
                            var name = SectionName(gi, ti);
                            var topic = g.Topics[ti];
                            toc.Item().PaddingLeft(14).Row(row =>
                            {
                                row.RelativeItem().Text(t =>
                                {
                                    t.SectionLink($"{gi + 1}.{ti + 1}  {topic.Title}", name);
                                    t.DefaultTextStyle(s => s.FontSize(9).FontColor("#00639E"));
                                });
                                row.ConstantItem(28).AlignRight().Text(t =>
                                {
                                    t.BeginPageNumberOfSection(name);
                                    t.DefaultTextStyle(s => s.FontSize(9).FontColor("#666666"));
                                });
                            });
                        }
                    }
                });

                root.Item().PageBreak();

                // ── Sections & topics ──────────────────────────────────────────
                for (var gi = 0; gi < pack.Groups.Count; gi++)
                {
                    var g = pack.Groups[gi];
                    root.Item().PaddingTop(gi == 0 ? 0 : 16).Text($"{gi + 1}. {g.Title}")
                        .Bold().FontSize(15).FontColor(Navy);
                    root.Item().PaddingTop(2).BorderBottom(2).BorderColor(Teal).PaddingBottom(2);

                    for (var ti = 0; ti < g.Topics.Count; ti++)
                    {
                        TopicCard(root.Item(), SectionName(gi, ti), $"{gi + 1}.{ti + 1}", g.Topics[ti]);
                    }
                }
            });

            page.Footer().BorderTop(0.8f).BorderColor(GreyBorder).PaddingTop(5).Row(footer =>
            {
                footer.RelativeItem().Text($"NT.QAMS User Manual · {pack.TenantName} · generated by {pack.GeneratedBy} at {pack.GeneratedAtUtc:u}")
                    .FontSize(7.5f).FontColor("#797979");
                footer.ConstantItem(80).AlignRight().Text(t =>
                {
                    t.DefaultTextStyle(s => s.FontSize(7.5f).FontColor("#797979"));
                    t.Span("Page ");
                    t.CurrentPageNumber();
                    t.Span(" of ");
                    t.TotalPages();
                });
            });
        })).GeneratePdf();
    }

    private static string SectionName(int groupIndex, int topicIndex) => $"topic-{groupIndex}-{topicIndex}";

    private static void OverviewTile(IContainer container, string value, string label)
    {
        container.Padding(3).Border(0.8f).BorderColor(GreyBorder).Background(GreyBg).Padding(10).Column(tile =>
        {
            tile.Item().Text(value).Bold().FontSize(22).FontColor(InkFor("blue"));
            tile.Item().PaddingTop(1).Text(label).FontSize(8.5f).FontColor("#666666");
        });
    }

    /// <summary>One topic: title, summary, a numbered progress bar over the steps, the steps, and the usage checklist. Kept together on a page where it fits.</summary>
    private static void TopicCard(IContainer container, string sectionName, string ordinal, ManualTopicDto topic)
    {
        container.Section(sectionName).PaddingTop(12).Column(card =>
        {
            card.Item().ShowEntire().Column(head =>
            {
                head.Item().Row(row =>
                {
                    row.RelativeItem().Text($"{ordinal}  {topic.Title}").Bold().FontSize(12).FontColor(Navy);
                    row.ConstantItem(140).AlignRight().Text(topic.Route).FontSize(8).Italic().FontColor("#999999");
                });
                if (!string.IsNullOrWhiteSpace(topic.Summary))
                {
                    head.Item().PaddingTop(3).Text(topic.Summary).FontSize(9).FontColor(Slate);
                }

                // Numbered progress bar over the workflow steps (mirrors the in-app help).
                if (topic.Steps.Count > 0)
                {
                    head.Item().PaddingTop(7).Height(16).Row(bar =>
                    {
                        for (var i = 0; i < topic.Steps.Count; i++)
                        {
                            bar.RelativeItem().PaddingRight(3).Background(InkFor("blue"))
                                .AlignCenter().AlignMiddle()
                                .Text((i + 1).ToString()).FontColor("#FFFFFF").FontSize(8.5f).Bold();
                        }
                    });
                }
            });

            // The steps, numbered, with their detail.
            for (var i = 0; i < topic.Steps.Count; i++)
            {
                var s = topic.Steps[i];
                card.Item().PaddingTop(4).Row(row =>
                {
                    row.ConstantItem(20).Text($"{i + 1}.").Bold().FontSize(9).FontColor(Teal);
                    row.RelativeItem().Column(c =>
                    {
                        c.Item().Text(s.Label).Bold().FontSize(9).FontColor(Slate);
                        if (!string.IsNullOrWhiteSpace(s.Detail))
                        {
                            c.Item().Text(s.Detail).FontSize(8.5f).FontColor("#555555");
                        }
                    });
                });
            }

            // "How to use" checklist.
            if (topic.Usage.Count > 0)
            {
                card.Item().PaddingTop(6).Text("How to use").Bold().FontSize(8.5f).FontColor(Slate);
                foreach (var u in topic.Usage)
                {
                    card.Item().PaddingTop(1).Row(row =>
                    {
                        row.ConstantItem(14).Text("✓").FontSize(8.5f).FontColor(InkFor("green"));
                        row.RelativeItem().Text(u).FontSize(8.5f).FontColor("#555555");
                    });
                }
            }

            card.Item().PaddingTop(8).LineHorizontal(0.5f).LineColor(GreyBorder);
        });
    }
}
