using ClosedXML.Excel;
using NT.QAMS.Application.Abstractions;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace NT.QAMS.Infrastructure.Exports;

/// <summary>
/// Part 11 §11.10(b) export rendering: real XLSX via ClosedXML (one worksheet
/// per table, provenance header, frozen header row) and paginated PDF via
/// QuestPDF (Community license) with the provenance stamp in every page
/// footer. Deliberately no HTML-as-xls tricks — these are inspection copies.
/// </summary>
public sealed partial class ExportService : IExportService
{
    static ExportService()
    {
        QuestPDF.Settings.License = LicenseType.Community;
    }

    public byte[] ToXlsx(ExportPack pack)
    {
        using var workbook = new XLWorkbook();
        var index = 1;
        foreach (var table in pack.Tables)
        {
            var sheet = workbook.Worksheets.Add(SheetName(table.Title, index++));

            sheet.Cell(1, 1).Value = pack.Title;
            sheet.Cell(1, 1).Style.Font.SetBold().Font.SetFontSize(14);
            sheet.Cell(2, 1).Value =
                $"Tenant: {pack.TenantName} · Generated by {pack.GeneratedBy} at {pack.GeneratedAtUtc:u} · {table.Title}";
            sheet.Cell(2, 1).Style.Font.SetItalic().Font.SetFontColor(XLColor.DimGray);

            const int headerRow = 4;
            for (var c = 0; c < table.Columns.Count; c++)
            {
                var cell = sheet.Cell(headerRow, c + 1);
                cell.Value = table.Columns[c];
                cell.Style.Font.SetBold();
                cell.Style.Fill.SetBackgroundColor(XLColor.FromHtml("#3B4658"));
                cell.Style.Font.SetFontColor(XLColor.White);
            }

            for (var r = 0; r < table.Rows.Count; r++)
            {
                for (var c = 0; c < table.Rows[r].Count; c++)
                {
                    sheet.Cell(headerRow + 1 + r, c + 1).Value = table.Rows[r][c];
                }
            }

            sheet.SheetView.FreezeRows(headerRow);
            sheet.Columns().AdjustToContents(1, Math.Min(headerRow + 50, headerRow + table.Rows.Count + 1));
        }

        using var stream = new MemoryStream();
        workbook.SaveAs(stream);
        return stream.ToArray();
    }

    public byte[] ToPdf(ExportPack pack)
    {
        return Document.Create(document => document.Page(page =>
        {
            page.Size(PageSizes.A4.Landscape());
            page.Margin(28);
            page.DefaultTextStyle(t => t.FontSize(9));

            page.Header().Column(header =>
            {
                header.Item().Text(pack.Title).Bold().FontSize(16).FontColor("#1E3A5F");
                header.Item().PaddingBottom(6).Text($"Tenant: {pack.TenantName}")
                    .FontSize(9).FontColor("#666666");
            });

            page.Content().Column(content =>
            {
                foreach (var table in pack.Tables)
                {
                    content.Item().PaddingTop(10).Text(table.Title).Bold().FontSize(11).FontColor("#3B4658");
                    content.Item().PaddingTop(4).Table(t =>
                    {
                        t.ColumnsDefinition(cols =>
                        {
                            foreach (var _ in table.Columns)
                            {
                                cols.RelativeColumn();
                            }
                        });

                        t.Header(h =>
                        {
                            foreach (var column in table.Columns)
                            {
                                h.Cell().Background("#3B4658").Padding(4)
                                    .Text(column).Bold().FontColor("#FFFFFF").FontSize(8.5f);
                            }
                        });

                        var zebra = false;
                        foreach (var row in table.Rows)
                        {
                            var background = zebra ? "#F7F7F7" : "#FFFFFF";
                            zebra = !zebra;
                            foreach (var value in row)
                            {
                                t.Cell().Background(background).BorderBottom(0.5f).BorderColor("#C1C1C6")
                                    .Padding(4).Text(value).FontSize(8.5f);
                            }
                        }
                    });
                }
            });

            page.Footer().Row(footer =>
            {
                footer.RelativeItem().Text(
                        $"Accurate and complete copy · generated by {pack.GeneratedBy} at {pack.GeneratedAtUtc:u}")
                    .FontSize(7.5f).FontColor("#797979");
                footer.RelativeItem().AlignRight().Text(t =>
                {
                    t.DefaultTextStyle(s => s.FontSize(7.5f).FontColor("#797979"));
                    t.Span("Page ");
                    t.CurrentPageNumber();
                    t.Span(" of ");
                    t.TotalPages();
                });
            });
        })).GeneratePdf();
    }

    // ── Branded register-page exports ────────────────────────────────────────

    /// <summary>The brand palette, mirrored from the SPA's design tokens.</summary>
    private const string Navy = "#1E3A5F";
    private const string Blue = "#0077C2";
    private const string Teal = "#00B2A9";
    private const string Slate = "#3B4658";
    private const string GreyBorder = "#C1C1C6";
    private const string GreyBg = "#F7F7F7";

    /// <summary>
    /// The readable ink ramp the SPA uses for statistic values — the saturated
    /// fill tones fail contrast as text, so exports use the same darkened steps.
    /// </summary>
    private static string InkFor(string? tone) => tone switch
    {
        "blue" => "#00639E",
        "teal" => "#00706A",
        "green" => "#12631F",
        "gold" => "#8A5A00",
        "orange" => "#B4430F",
        "red" => "#B3202D",
        _ => "#4A5768",
    };

    public byte[] ToPageXlsx(PageExportPack pack)
    {
        using var workbook = new XLWorkbook();
        var sheet = workbook.Worksheets.Add(SheetName(pack.Title, 1));

        // Provenance band.
        sheet.Cell(1, 1).Value = pack.Title;
        sheet.Cell(1, 1).Style.Font.SetBold().Font.SetFontSize(16).Font.SetFontColor(XLColor.FromHtml(Navy));
        sheet.Cell(2, 1).Value =
            $"Tenant: {pack.TenantName} · Generated by {pack.GeneratedBy} at {pack.GeneratedAtUtc:u}";
        sheet.Cell(2, 1).Style.Font.SetItalic().Font.SetFontColor(XLColor.DimGray);
        var row = 3;
        if (!string.IsNullOrWhiteSpace(pack.FiltersSummary))
        {
            sheet.Cell(row, 1).Value = $"Filters: {pack.FiltersSummary}";
            sheet.Cell(row, 1).Style.Font.SetItalic().Font.SetFontColor(XLColor.DimGray);
            row++;
        }

        // Statistic tiles: label over value, one column pair per stat.
        if (pack.Stats.Count > 0)
        {
            row++;
            for (var i = 0; i < pack.Stats.Count; i++)
            {
                var labelCell = sheet.Cell(row, i + 1);
                labelCell.Value = pack.Stats[i].Label;
                labelCell.Style.Font.SetFontSize(8).Font.SetFontColor(XLColor.FromHtml("#797979"));
                var valueCell = sheet.Cell(row + 1, i + 1);
                valueCell.Value = pack.Stats[i].Value;
                GuardFormulaLike(valueCell, pack.Stats[i].Value);
                valueCell.Style.Font.SetBold().Font.SetFontSize(13)
                    .Font.SetFontColor(XLColor.FromHtml(InkFor(pack.Stats[i].Tone)));
                sheet.Range(row, i + 1, row + 1, i + 1).Style
                    .Fill.SetBackgroundColor(XLColor.FromHtml(GreyBg))
                    .Border.SetOutsideBorder(XLBorderStyleValues.Thin)
                    .Border.SetOutsideBorderColor(XLColor.FromHtml(GreyBorder));
            }

            row += 3;
        }
        else
        {
            row++;
        }

        // Grid with frozen, filterable header.
        var headerRow = row;
        for (var c = 0; c < pack.Table.Columns.Count; c++)
        {
            var cell = sheet.Cell(headerRow, c + 1);
            cell.Value = pack.Table.Columns[c];
            cell.Style.Font.SetBold();
            cell.Style.Fill.SetBackgroundColor(XLColor.FromHtml(Slate));
            cell.Style.Font.SetFontColor(XLColor.White);
        }

        for (var r = 0; r < pack.Table.Rows.Count; r++)
        {
            for (var c = 0; c < pack.Table.Rows[r].Count; c++)
            {
                var cell = sheet.Cell(headerRow + 1 + r, c + 1);
                cell.Value = pack.Table.Rows[r][c];
                GuardFormulaLike(cell, pack.Table.Rows[r][c]);
            }
        }

        if (pack.Table.Rows.Count > 0)
        {
            sheet.Range(headerRow, 1, headerRow + pack.Table.Rows.Count, pack.Table.Columns.Count)
                .SetAutoFilter();
        }

        sheet.SheetView.FreezeRows(headerRow);
        sheet.Columns().AdjustToContents(1, Math.Min(headerRow + 50, headerRow + pack.Table.Rows.Count + 1));

        using var stream = new MemoryStream();
        workbook.SaveAs(stream);
        return stream.ToArray();
    }

    public byte[] ToPagePdf(PageExportPack pack)
    {
        return Document.Create(document => document.Page(page =>
        {
            page.Size(pack.Table.Columns.Count > 6 ? PageSizes.A4.Landscape() : PageSizes.A4);
            page.Margin(30);
            page.DefaultTextStyle(t => t.FontSize(9).FontColor(Slate));

            page.Header().Column(header =>
            {
                // Brand band: navy rule, title, provenance, filters-in-force.
                header.Item().BorderBottom(3).BorderColor(Blue).PaddingBottom(8).Row(band =>
                {
                    band.RelativeItem().Column(left =>
                    {
                        left.Item().Text(pack.Title).Bold().FontSize(18).FontColor(Navy);
                        left.Item().PaddingTop(2).Text(pack.TenantName).FontSize(10).FontColor(Teal).Bold();
                    });
                    band.ConstantItem(220).AlignRight().Column(right =>
                    {
                        right.Item().AlignRight().Text($"{pack.GeneratedAtUtc:yyyy-MM-dd HH:mm} UTC")
                            .FontSize(8.5f).FontColor("#666666");
                        right.Item().AlignRight().Text(pack.GeneratedBy).FontSize(8.5f).FontColor("#666666");
                    });
                });

                if (!string.IsNullOrWhiteSpace(pack.FiltersSummary))
                {
                    header.Item().PaddingTop(6).Text($"Filters: {pack.FiltersSummary}")
                        .FontSize(8.5f).Italic().FontColor("#666666");
                }
            });

            page.Content().PaddingTop(10).Column(content =>
            {
                // Statistic tiles, as shown on screen: value in its readable ink,
                // label beneath — colour is never the only carrier of meaning.
                if (pack.Stats.Count > 0)
                {
                    content.Item().PaddingBottom(12).Row(tiles =>
                    {
                        foreach (var stat in pack.Stats)
                        {
                            tiles.RelativeItem().Padding(2).Border(0.8f).BorderColor(GreyBorder)
                                .Background(GreyBg).Padding(7).Column(tile =>
                                {
                                    tile.Item().Text(stat.Value).Bold().FontSize(15)
                                        .FontColor(InkFor(stat.Tone));
                                    tile.Item().PaddingTop(1).Text(stat.Label)
                                        .FontSize(7.2f).FontColor("#666666");
                                });
                        }
                    });
                }

                content.Item().Table(t =>
                {
                    t.ColumnsDefinition(cols =>
                    {
                        foreach (var _ in pack.Table.Columns)
                        {
                            cols.RelativeColumn();
                        }
                    });

                    t.Header(h =>
                    {
                        foreach (var column in pack.Table.Columns)
                        {
                            h.Cell().Background(Slate).Padding(5)
                                .Text(column).Bold().FontColor("#FFFFFF").FontSize(8.5f);
                        }
                    });

                    var zebra = false;
                    foreach (var dataRow in pack.Table.Rows)
                    {
                        var background = zebra ? GreyBg : "#FFFFFF";
                        zebra = !zebra;
                        foreach (var value in dataRow)
                        {
                            t.Cell().Background(background).BorderBottom(0.5f).BorderColor(GreyBorder)
                                .Padding(4.5f).Text(value).FontSize(8.5f);
                        }
                    }
                });

                content.Item().PaddingTop(6)
                    .Text($"{pack.Table.Rows.Count} records")
                    .FontSize(8).Italic().FontColor("#797979");
            });

            page.Footer().BorderTop(0.8f).BorderColor(GreyBorder).PaddingTop(5).Row(footer =>
            {
                footer.RelativeItem().Text(
                        $"Accurate and complete copy of the record as visible to {pack.GeneratedBy} · " +
                        "21 CFR Part 11 §11.10(b) · NT.QAMS")
                    .FontSize(7.5f).FontColor("#797979");
                footer.ConstantItem(80).AlignRight().Text(t =>
                {
                    t.DefaultTextStyle(s => s.FontSize(7.5f).FontColor("#797979"));
                    t.Span("Page ");
                    t.CurrentPageNumber();
                    t.Span(" of ");
                    t.TotalPages();
                });
            });
        })).GeneratePdf();
    }

    /// <summary>
    /// Excel formula-injection defence for client-supplied text. ClosedXML
    /// already writes string-typed cells (never &lt;f&gt; formula elements), so a
    /// value beginning with = cannot execute; the explicit quote prefix marks it
    /// as deliberate text on top, so a later copy-paste or re-save does not
    /// reinterpret it either. (A string-prefixed apostrophe does not survive
    /// ClosedXML — it strips it as the classic text marker — hence the style flag.)
    /// </summary>
    private static void GuardFormulaLike(IXLCell cell, string value)
    {
        if (value.Length > 0 && value[0] is '=' or '+' or '@')
        {
            cell.Style.IncludeQuotePrefix = true;
        }
    }

    /// <summary>Worksheet names cap at 31 chars and must be unique per workbook.</summary>
    private static string SheetName(string title, int index)
    {
        var cleaned = new string(title.Where(ch => ch is not ('\\' or '/' or '*' or '[' or ']' or ':' or '?')).ToArray());
        var trimmed = cleaned.Length > 27 ? cleaned[..27] : cleaned;
        return $"{index:00} {trimmed}".Trim();
    }
}
